### ISSUE TITLE
Font colors that work good with both light and dark themes

### ISSUE THREAD

**Issue by DefaultUser** [DefaultUser/PyTIBot#5]
The currently used colors for Git webhook messages are not optimal especially for users of Element's dark mode.
This issue is intended to collect opinions and suggestions. These should consider IRC's limited color range (https://github.com/DefaultUser/PyTIBot/blob/internal_representations/util/formatting/common.py#L57-L73).

Current message definitions are here: https://github.com/DefaultUser/PyTIBot/blob/internal_representations/lib/git_webhook.py

**Comment by bones-was-here** [comment]
I suggest using `magenta` for all branch names, currently they're green in some places, `darkred` in some places, and `magenta` in others.  Green and red are used for other things too and for consistency it would be nice if branches were always the same colour.

`magenta` is more readable than `darkmagenta`.
`red` or `#FF0000` is more readable than `darkred`.

**Comment by bones-was-here** [comment]
On gitlab specifically it would be possible to save some characters by omitting "Issue" and "Merge Request" because the `#` or `!` indicates which one it is.

**Comment by bones-was-here** [comment]
Also IMO the repo names could be in the default colour, it should be clear in any them.  Green is used for some other things and the repo names have the `[]` and are always at the start of line, which should be enough to make them distinct.

**Comment by DefaultUser** [comment]
The change for green comes from using color names instead of hex values. I will probably change that back.

**Comment by DefaultUser** [comment]
The new default colors look good enough with both dark and light themes. Additionally, git webhook messages and messages from the vote module are now adjustable via config. I consider this issue fixed.
